stages:
- code analysis
- test
- deploy

variables:
  GET_SOURCES_ATTEMPTS: 3
  PIP_INDEX: https://nexus.web.sandia.gov/repository/pypi-proxy/pypi
  PIP_INDEX_URL: https://nexus.web.sandia.gov/repository/pypi-proxy/simple
  PIP_TRUSTED_HOST: nexus.web.sandia.gov
  STD_PIP_ARGS: "--trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org"
  CONDA_PYTHON3: /usr/local/anaconda/3-2024.02/bin/python3


before_script:
- $CONDA_PYTHON3 -m venv venv
- source venv/bin/activate
- python3 --version


unit-test:
  stage: test
  tags:
  - cee.build
  script:
  - module use /projects/aue/modules/cee/x86_64/rhel8 > /dev/null 2>&1 || true
  - module load aue/cmake/3.27.7 > /dev/null 2>&1 || true
  - module load aue/gcc/12.1.0 > /dev/null 2>&1 || true
  - module load aue/openmpi/4.1.6-gcc-12.1.0 > /dev/null 2>&1 || true
  - python3 -m pip install $STD_PIP_ARGS -e .[dev,slurm,pbs,flux,psutil]
  - pytest tests
  rules:
  - if: $RUN_UNIT_TESTS
    when: always


coverage-test:
  stage: test
  tags:
  - cee.build
  script:
  - module use /projects/aue/modules/cee/x86_64/rhel8 > /dev/null 2>&1 || true
  - module load aue/cmake/3.27.7 > /dev/null 2>&1 || true
  - module load aue/gcc/12.1.0 > /dev/null 2>&1 || true
  - module load aue/openmpi/4.1.6-gcc-12.1.0 > /dev/null 2>&1 || true
  - python3 -m pip install $STD_PIP_ARGS -e .[dev,slurm,pbs,flux,psutil]
  - coverage run
  - coverage report
  - coverage xml
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    when: always
  coverage: '/TOTAL.*? (100(?:\.0+)?\%\|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    reports:
      coverage_report:
        path: coverage.xml
        coverage_format: cobertura


lint-changed-files:
  stage: code analysis
  tags:
  - cee.build
  script:
  - python3 -m pip install $STD_PIP_ARGS ruff
  - ruff --version
  - git fetch origin "${CI_MERGE_REQUEST_TARGET_BRANCH_NAME:?}"
  - ./bin/ci/ruff-check --ref="origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME:?}" --output-format=junit --output-file=ruff.xml
  - cat ruff.xml
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    when: always
  artifacts:
    when: always
    reports:
      junit: ruff.xml


format-changed-files:
  stage: code analysis
  tags:
  - cee.build
  script:
  - python3 -m pip install $STD_PIP_ARGS ruff
  - ruff --version
  - git fetch origin "${CI_MERGE_REQUEST_TARGET_BRANCH_NAME:?}"
  - ./bin/ci/ruff-format --ref="origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME:?}" --check
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    when: always


mypy:
  stage: code analysis
  tags:
  - cee.build
  script:
  - python3 -m pip install $STD_PIP_ARGS -e .[dev,slurm,pbs,flux,psutil]
  - python3 -m pip install $STD_PIP_ARGS mypy mypy-gitlab-code-quality
  - mypy ./src --no-error-summary > mypy-out.txt || true
  - mypy-gitlab-code-quality < mypy-out.txt > codequality.json
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    when: always
  artifacts:
    when: always
    reports:
      codequality: codequality.json
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    when: always


.pages:
  stage: deploy
  tags:
  - cee.build
  script:
  - python3 -m pip install $STD_PIP_ARGS .[dev,slurm,pbs,flux]
  - cd docs
  - make clean
  - make html
  - make html
  - cd ..
  - rm -rf public
  - mv docs/build/html public
  - deactivate


pages:
  extends: .pages
  variables:
    GIT_STRATEGY: clone
  before_script:
  # make sure to install from main to get the right version number
  - git checkout main
  - git pull
  - git fetch --tags
  - $CONDA_PYTHON3 -m venv venv
  - source venv/bin/activate
  - python3 --version
  rules:
  - if: ($CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main")
    changes:
    - src/nvtest/directives.py
    - src/_nvtest/plugins/commands/*.py
    - docs/*.rst
    - docs/*/*.rst
    - docs/**/*.rst
    - docs/Makefile
    - docs/source/conf.py
    - docs/source/dot/*.png
    - docs/source/images/*.png
    when: always
  - if: $BUILD_PAGES
    when: always
  artifacts:
    paths:
    - public


mr-pages:
  extends: .pages
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    changes:
    - src/nvtest/directives.py
    - src/_nvtest/plugins/commands/*.py
    - docs/*.rst
    - docs/*/*.rst
    - docs/**/*.rst
    - docs/Makefile
    - docs/source/conf.py
    - docs/source/dot/*.png
    - docs/source/images/*.png
    when: always
