stages:
- test
- deploy

variables:
  GET_SOURCES_ATTEMPTS: 3
  BASE_CEE_PYTHON3: /usr/local/anaconda/3-2024.02/bin/python3
  PIP_INDEX: https://nexus.web.sandia.gov/repository/pypi-proxy/pypi
  PIP_INDEX_URL: https://nexus.web.sandia.gov/repository/pypi-proxy/simple
  PIP_TRUSTED_HOST: nexus.web.sandia.gov
  STD_PIP_ARGS: "--trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org"

test-job:
  tags:
  - cee.build
  stage: test
  script:
  - module use /projects/aue/modules/cee/x86_64/rhel8 > /dev/null 2>&1 || true
  - module load aue/cmake/3.27.7 > /dev/null 2>&1 || true
  - module load aue/gcc/12.1.0 > /dev/null 2>&1 || true
  - module load aue/openmpi/4.1.4-gcc-12.1.0 > /dev/null 2>&1 || true
  - $BASE_CEE_PYTHON3 -m venv venv
  - python3 -m venv venv
  - source venv/bin/activate
  - python3 -m pip install $STD_PIP_ARGS -e .[dev]
  - pytest ./tests
  - deactivate
  rules:
  - if: ($CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main")
    when: always

pages:
  stage: deploy
  tags:
  - cee.build
  script:
  - $BASE_CEE_PYTHON3 -m venv venv
  - source ./venv/bin/activate
  - python3 -m pip install $STD_PIP_ARGS -e .[dev]
  - cd docs
  - make clean
  - make html
  - make html
  - cd ..
  - rm -rf public
  - mv docs/build/html public
  - deactivate
  artifacts:
    paths:
    - public
  rules:
  - if: ($CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main")
    changes:
    - src/nvtest/directives.py
    - src/_nvtest/plugins/commands/*.py
    - docs/*.rst
    - docs/*/*.rst
    - docs/**/*.rst
    - docs/Makefile
    - docs/source/conf.py
    - docs/source/dot/*.png
    - docs/source/images/*.png
    when: always
  - if: $BUILD_PAGES
    when: always
