stages:
- deploy

pages:
  stage: deploy
  script:
  - module use /projects/alegranevada/modules/cee/linux_rh7
  - module load python/3.9
  - pip install -u -e .
  - cd docs
  - make clean
  - make html
  - cd ..
  - rm -rf public
  - mv docs/build/html public
  artifacts:
    paths:
    - public
  rules:
  - if: ($CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main")
    changes:
    - docs/*.rst
    - docs/*/*.rst
    - docs/**/*.rst
    - docs/Makefile
    - .gitlab-ci.yml
    when: always
