stages:
- test
- deploy

test-job:
  stage: test
  script:
  - /projects/alegranevada/opt/cee/linux_rh7/python/3.9/bin/python -m venv venv
  - source venv/bin/activate
  - python -m pip install -e .
  - python -m pip install pytest
  - cd tests
  - pytest .
  - cd ..
  - deactivate
  rules:
  - if: ($CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main")
    when: always


pages:
  stage: deploy
  script:
  - /projects/alegranevada/opt/cee/linux_rh7/python/3.9/bin/python -m venv venv
  - source venv/bin/activate
  - python -m pip install -e .
  - cd docs
  - make clean
  - make html
  - cd ..
  - rm -rf public
  - mv docs/build/html public
  - deactivate
  artifacts:
    paths:
    - public
  rules:
  - if: ($CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main")
    changes:
    - docs/*.rst
    - docs/*/*.rst
    - docs/**/*.rst
    - docs/Makefile
    - .gitlab-ci.yml
    when: always
