stages:
- test
- deploy

test-job:
  tags: [cee]
  stage: test
  script:
  - module use /projects/alegranevada/modules/$SNLSYSTEM/$SNLCLUSTER
  - module use /projects/aue/modules/cee/x86_64/rhel8 > /dev/null 2>&1 || true
  - module load aue/cmake/3.27.7 > /dev/null 2>&1 || true
  - module load aue/gcc/12.1.0 > /dev/null 2>&1 || true
  - module load aue/openmpi/4.1.4-gcc-12.1.0 > /dev/null 2>&1 || true
  - module load alegra-dev
  - python3 -m venv venv
  - source venv/bin/activate
  - python3 -m pip install -e .[dev]
  - pytest ./tests
  - deactivate
  rules:
  - if: ($CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main")
    when: always

pages:
  stage: deploy
  tags: [cee]
  script:
  - module use /projects/alegranevada/modules/$SNLSYSTEM/$SNLCLUSTER
  - module load alegra-dev
  - python3 -m venv venv
  - source venv/bin/activate
  - python3 -m pip install -e .[dev]
  - cd docs
  - make clean
  - make html
  - cd ..
  - rm -rf public
  - mv docs/build/html public
  - deactivate
  artifacts:
    paths:
    - public
  rules:
  - if: ($CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main")
    changes:
    - src/_nvtest/directives/*.py
    - src/_nvtest/commands/*.py
    - src/_nvtest/test/testfile.py
    - docs/*.rst
    - docs/*/*.rst
    - docs/**/*.rst
    - docs/Makefile
    - docs/source/conf.py
    when: always
