stages:
- test
- deploy

test-job:
  tags:
  - cee
  - linux_rh7
  stage: test
  script:
  - module use /projects/aue/modules/cee/x86_64/rhel7 > /dev/null 2>&1 || true
  - module load aue/cmake/3.27.7 > /dev/null 2>&1 || true
  - module load aue/gcc/12.1.0 > /dev/null 2>&1 || true
  - module load aue/openmpi/4.1.4-gcc-12.1.0 > /dev/null 2>&1 || true
  - /projects/alegranevada/opt/cee/linux_rh7/python/3.9/bin/python -m venv venv
  - source venv/bin/activate
  - python -m pip install -e .[dev]
  - pytest ./tests
  - deactivate
  rules:
  - if: ($CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main")
    when: always

pages:
  stage: deploy
  tags:
  - cee
  - linux_rh7
  script:
  - /projects/alegranevada/opt/cee/linux_rh7/python/3.9/bin/python -m venv venv
  - source venv/bin/activate
  - python -m pip install -e .[dev]
  - cd docs
  - make clean
  - make html
  - cd ..
  - rm -rf public
  - mv docs/build/html public
  - deactivate
  artifacts:
    paths:
    - public
  rules:
  - if: ($CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main")
    changes:
    - src/_nvtest/directives/*.py
    - src/_nvtest/commands/*.py
    - src/_nvtest/tests/howto/*.py
    - src/_nvtest/test/testfile.py
    - docs/*.rst
    - docs/*/*.rst
    - docs/**/*.rst
    - docs/Makefile
    - docs/source/conf.py
    when: always
