stages:
- code analysis
- test
- deploy

variables:
  GET_SOURCES_ATTEMPTS: 3
  PIP_INDEX: https://nexus.web.sandia.gov/repository/pypi-proxy/pypi
  PIP_INDEX_URL: https://nexus.web.sandia.gov/repository/pypi-proxy/simple
  PIP_TRUSTED_HOST: nexus.web.sandia.gov
  STD_PIP_ARGS: "--trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org"


before_script:
- /usr/local/anaconda/3-2024.02/bin/python3 -m venv venv
- source venv/bin/activate
- python3 --version


test-job:
  stage: test
  tags:
  - cee.build
  script:
  - module use /projects/aue/modules/cee/x86_64/rhel8 > /dev/null 2>&1 || true
  - module load aue/cmake/3.27.7 > /dev/null 2>&1 || true
  - module load aue/gcc/12.1.0 > /dev/null 2>&1 || true
  - module load aue/openmpi/4.1.4-gcc-12.1.0 > /dev/null 2>&1 || true
  - python3 -m pip install $STD_PIP_ARGS -e .[dev]
  - pytest ./tests
  - deactivate
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
    when: always

lint-changed-files:
  stage: code analysis
  tags:
  - cee.build
  script:
  - python3 -m pip install $STD_PIP_ARGS ruff
  - ruff --version
  - git fetch origin "${CI_MERGE_REQUEST_TARGET_BRANCH_NAME:?}"
  - ./bin/ci/ruff "origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME:?}" check --output-format=junit --output-file=ruff.xml
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
    when: always
  artifacts:
    when: always
    reports:
      junit: ruff.xml

format-changed-files:
  stage: code analysis
  tags:
  - cee.build
  script:
  - python3 -m pip install $STD_PIP_ARGS ruff
  - ruff --version
  - git fetch origin "${CI_MERGE_REQUEST_TARGET_BRANCH_NAME:?}"
  - ./bin/ci/ruff "origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME:?}" format --check
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
    when: always

mypy:
  stage: code analysis
  tags:
  - cee.build
  script:
  - python3 -m pip install $STD_PIP_ARGS mypy mypy-gitlab-code-quality
  - mypy ./src --no-error-summary > mypy-out.txt || true
  - mypy-gitlab-code-quality < mypy-out.txt > codequality.json
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
    when: always
  artifacts:
    when: always
    reports:
      codequality: codequality.json
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
    when: always


.pages:
  stage: deploy
  tags:
  - cee.build
  script:
  - python3 -m pip install $STD_PIP_ARGS -e .[dev]
  - cd docs
  - make clean
  - make html
  - make html
  - cd ..
  - rm -rf public
  - mv docs/build/html public
  - deactivate

pages:
  extends: .pages
  rules:
  - if: ($CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main")
    changes:
    - src/nvtest/directives.py
    - src/_nvtest/plugins/commands/*.py
    - docs/*.rst
    - docs/*/*.rst
    - docs/**/*.rst
    - docs/Makefile
    - docs/source/conf.py
    - docs/source/dot/*.png
    - docs/source/images/*.png
    when: always
  - if: $BUILD_PAGES
    when: always
  artifacts:
    paths:
    - public

mr-pages:
  extends: .pages
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
    changes:
    - src/nvtest/directives.py
    - src/_nvtest/plugins/commands/*.py
    - docs/*.rst
    - docs/*/*.rst
    - docs/**/*.rst
    - docs/Makefile
    - docs/source/conf.py
    - docs/source/dot/*.png
    - docs/source/images/*.png
    when: always
