[project]
name = "nvtest"
dynamic = ["version"]
readme = "README.md"
license = {"file" = "LICENSE"}
description = "nvtest: application testing with Python"
requires-python = ">=3.9"

[project.scripts]
nvtest = "nvtest:console_main"

[project.optional-dependencies]
dev = ["ruff", "mypy", "pytest", "sphinxcontrib-programoutput==0.17"]

[build-system]
requires = ["setuptools>=64", "setuptools-scm[toml]>=6.2.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/_nvtest/_version.py"

[tool.mypy]
exclude = [
    "scripts",
    "src/_nvtest/third_party/distro.py"
]

[[tool.mypy.overrides]]
module = "networkx.*,yaml.*,ruamel.*,pygments.*,toml.*,contextlib2.*,scipy.*,_nvtest.tests.*,numpy.*,imageio.*"
ignore_missing_imports = true


# check-wheel-contents is executed by the build-and-inspect-python-package action.
[tool.check-wheel-contents]
# W009: Wheel contains multiple toplevel library entries
ignore = "W009"

[tool.ruff]
target-version = "py39"

[tool.ruff.per-file-ignores]
"src/_nvtest/schemas/__init__.py" = ["F401"]
"src/nvtest/__init__.py" = ["F401"]
"src/_nvtest/user/diffutils/__init__.py" = ["F401"]
"src/_nvtest/reporters/__init__.py" = ["F401"]

[tool.ruff.lint]
ignore = ["E741", "F841", "E731"]
