[project]
name = "nvtest"
dynamic = ["version"]
readme = "README.md"
license = {"file" = "LICENSE"}
description = "nvtest: application testing with Python"
requires-python = ">=3.9"
dependencies = []

[project.scripts]
nvtest = "nvtest:console_main"

[project.optional-dependencies]
dev = ["ruff", "mypy", "pytest", "sphinx"]
requests = ["requests"]

[build-system]
requires = ["setuptools>=64", "setuptools-scm[toml]>=6.2.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_file = "src/_nvtest/_version.py"
version_scheme = "guess-next-dev"
local_scheme = "node-and-date"

[tool.mypy]
exclude = ["src/_nvtest/third_party/distro.py", "src/_nvtest/third_party/programoutput/*", "src/_nvtest/third_party/monkeypatch.py"]

[[tool.mypy.overrides]]
module = "requests.*,networkx.*,yaml.*,ruamel.*,pygments.*,toml.*,contextlib2.*,scipy.*,pyinstrument.*,numpy.*,imageio.*,pkg_resources.*,dill.*"
ignore_missing_imports = true

# check-wheel-contents is executed by the build-and-inspect-python-package action.
[tool.check-wheel-contents]
# W009: Wheel contains multiple toplevel library entries
ignore = "W009"

[tool.ruff]
target-version = "py39"
line-length = 99

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"

[tool.ruff.lint.isort]
force-single-line = true

[tool.ruff.lint]
ignore = ["E741", "F841", "E731"]
select = ["F", "I"]

[tool.ruff.lint.per-file-ignores]
"src/_nvtest/schemas/__init__.py" = ["F401"]
"src/nvtest/__init__.py" = ["F401"]
"src/_nvtest/user/diffutils/__init__.py" = ["F401"]
"src/_nvtest/reporters/__init__.py" = ["F401"]
"src/_nvtest/third_party/*.py" = ["F401", "F403", "F405"]
