name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build the Slurm Docker Image
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "Building for branch: $BRANCH_NAME"
          docker build --build-arg BRANCH_NAME=$BRANCH_NAME --file docker/slurm/Dockerfile --tag slurm-test ./docker/slurm
          
      - name: Run tests
        run: |
          docker run --rm slurm-test /bin/bash -c "./test.sh"

