name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

        #  unit:
        #    runs-on: ubuntu-latest
        #    steps:
        #      - uses: actions/checkout@v4
        #      - name: Build canary image
        #        run: |
        #          BRANCH_NAME=${GITHUB_REF#refs/heads/}
        #          echo "Building for branch: $BRANCH_NAME"
        #          docker build --build-arg BRANCH_NAME=$BRANCH_NAME --file docker/standalone/Dockerfile --tag unit-test ./docker/standalone
        #      - name: Run unit tests
        #        run: docker run --rm unit-test ./test.sh
        #
        #  slurm:
        #    runs-on: ubuntu-latest
        #    steps:
        #      - uses: actions/checkout@v4
        #      - name: Build the Slurm Docker image
        #        run: |
        #          BRANCH_NAME=${GITHUB_REF#refs/heads/}
        #          echo "Building for branch: $BRANCH_NAME"
        #          docker build --build-arg BRANCH_NAME=$BRANCH_NAME --file docker/slurm/Dockerfile --tag slurm-test ./docker/slurm
        #      - name: Run Slurm tests
        #        run: |
        #          docker run --rm slurm-test /bin/bash -c "./test.sh"

  flux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pull the Flux Docker image
        run: |
          docker pull fluxrm/flux-sched:latest
      - name: Run Flux tests
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "Building for branch: $BRANCH_NAME"
          docker run --rm --user root -v /home/runner/work/canary/canary/docker/flux/test.sh:/home/fluxuser/test.sh fluxrm/flux-sched:latest flux start --test-size=2 ./test.sh $BRANCH_NAME
